// Generated by CoffeeScript 1.10.0
(function() {
  var app, browserWindow, electron, mainWindow, shell;

  electron = require('electron');

  app = electron.app;

  browserWindow = electron.BrowserWindow;

  shell = electron.shell;

  mainWindow = null;

  app.on('window-all-closed', function() {
    if (process.paltform !== 'darwin') {
      return app.quit();
    }
  });

  app.on('ready', function() {
    mainWindow = new browserWindow({
      width: 800,
      height: 600
    });
    mainWindow.loadURL("https://web.telegram.com");
    mainWindow.webContents.openDevTools();
    return mainWindow.on('closed', function() {
      return mainWindow = null;
    });
  });

}).call(this);
